---
services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/:/config
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.speedtest.entrypoints=http
      - traefik.http.routers.speedtest.rule=Host(`speedtest.${LOCAL_DOMAIN_NAME}`)
      - traefik.http.middlewares.speedtest-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.speedtest.middlewares=speedtest-https-redirect
      - traefik.http.routers.speedtest-secure.entrypoints=https
      - traefik.http.routers.speedtest-secure.rule=Host(`speedtest.${LOCAL_DOMAIN_NAME}`)
      - traefik.http.routers.speedtest-secure.tls=true
      - traefik.http.routers.speedtest-secure.service=speedtest
      - traefik.http.services.speedtest.loadbalancer.server.port=80
      - traefik.http.routers.speedtest.tls.certresolver=cloudflare

networks:
  default:
    name: reverseproxy-nw
    external: true
