---
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    network_mode: host
    volumes:
      - ./work/:/opt/adguardhome/work
      - ./conf/:/opt/adguardhome/conf
    restart: always
