---
- Services:
    - Adguard:
        icon: adguard-home.png
        href: http://your-pi-ip-here:8080
        description: Advanced DNS Management, Privacy Protection, and Network Control
    - Portainer:
        icon: portainer.png
        href: https://portainer.local.lowie.xyz/
        description: Docker Container Management
        widget:
          type: portainer
          url: https://portainer:9443
          env: 2
          key: changeme
    - Speedtest:
        icon: librespeed.png
        href: https://speedtest.local.lowie.xyz/
        description: Local Network Speedtest
    - Traefik:
        icon: traefik.png
        href: https://traefik.local.lowie.xyz/
        description: Reverse Proxy & Load Balancer
    - Watchtower:
        icon: watchtower.png
        description: Docker Image Updates
