---
- name: Install samba
  ansible.builtin.apt:
    name:
      - samba

- name: Insert/Update samba config file
  ansible.builtin.blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [admin]
      comment = Samba share
      path = /home/{{ user }}/appdata
      read only = no
      browsable = yes

- name: Restart smbd service
  ansible.builtin.systemd_service:
    name: smbd
    state: restarted
    enabled: true
  changed_when: false
